### ISSUE TITLE
DEMO

### ISSUE THREAD

**Issue by jedie** [neocotic/qr.js#34]
What's about to add a simple DEMO via 'gh-pages' ?

Something like this: https://jedie.github.io/qr.js.demo/

**Comment by neocotic** [comment]
@jedie, there is already an interactive demo on the project homepage (link at the bottom of the page): http://neocotic.com/qr.js

**Comment by jedie** [comment]
Oh, sorry. Didn't "see" the homepage...

Maybe move the homepage Link in README at the top?
And change the Link from **http://neocotic.com/qr.js** to **http://neocotic.com/qr.js/** (add slash, so it doesn't look like a file-download-link)

And move the DEMO Link on http://neocotic.com/qr.js/ also to the top? It's a little bit "hidden" and can be easily overlooked ;)
