### ISSUE TITLE
Consider using double license GPL/MIT

### ISSUE THREAD

**Issue by jlowcs** [neocotic/qr.js#43]
I'd like to use your library for a professional project. GPL license is not an option, therefore I cannot use it. Any reason why you didn't choose the MIT licence?

**Comment by neocotic** [comment]
This library was a massive rewrite of [jsqrencode](https://code.google.com/archive/p/jsqrencode/) which was released under GPLv3. One of the conditions of the GPLv3 license is that any modifications within redistributions must use the same license. I use MIT for any project that I create but it is too permissive in this case and would not comply with the GPLv3 license attached to the original project.

I'm not a big fan of GPL, but can I ask why you do not feel that it is an option for your project?

**Comment by jlowcs** [comment]
Ok, that makes sense. Too bad then.

It's company policy not to use librairies under GPL licence. Although we do have some open-sources librairies, our products are not open-source, and the company doesn't want to make the source code available.
