### ISSUE TITLE
Doesn't generate valid QR codes?

### ISSUE THREAD

**Issue by Timmmm** [neocotic/qr.js#46]
Hi,

I'm using version 1.1.4 with the example code to generate "Hello". It makes this QR code:

![hello](https://cloud.githubusercontent.com/assets/376842/16228401/ae38d124-37ae-11e6-8eb1-ea1be12a154b.png)

I tried scanning it with Android's Barcode Scanner app but it doesn't seem to be a valid QR code. I can't see that I'm doing anything wrong...

**Comment by neocotic** [comment]
@Timmmm, this is a valid QR code for "Hello". You might want to try another app. I've just tested the above image successfully on the following Android apps:

* [Goggles](https://play.google.com/store/apps/details?id=com.google.android.apps.unveil)
* [QR Code Reader](https://play.google.com/store/apps/details?id=me.scan.android.client)

**Comment by Timmmm** [comment]
Ah yes it turns out ZXing (used in Google's Barcode Scanner app) doesn't work when you're too close to the code, even though it detects the alignment points correctly. Very strange.
