### ISSUE TITLE
Support non-text QR codes

### ISSUE THREAD

**Issue by Timmmm** [neocotic/qr.js#47]
I can't see a way to encode non-text QR codes, e.g. URLs or binary data.

**Comment by neocotic** [comment]
@Timmmm, URLs are text values and can indeed be encoded as QR codes using this library.

As for binary data, the scanner would need to be able to understand how to rebuild the binary data (e.g. via a MIME type) so, if QRs can support this, I imagine there has to be some sort of standard for doing so. I'm not familiar with this but would welcome a PR from someone that is and can back it up with proof of support and some level of compliance.
